include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable rules that cause issues in this project
    use_key_in_widget_constructors: false
    library_private_types_in_public_api: false
    use_build_context_synchronously: false
    prefer_const_constructors_in_immutables: false

analyzer:
  errors:
    const_with_non_const: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
