// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn-uiKeWj3dL07v4H5NU9zeANed_phla0',
    appId: '1:582453672018:web:3b78bcb284d6e2d757478b',
    messagingSenderId: '582453672018',
    projectId: 'lab10-80335',
    authDomain: 'lab10-80335.firebaseapp.com',
    storageBucket: 'lab10-80335.firebasestorage.app',
    measurementId: 'G-2YSG45LX1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALC4TZ8BWbtq0O1E5aw_GYA3iI7hr5F0Y',
    appId: '1:582453672018:android:d849bba27a43ba3d57478b',
    messagingSenderId: '582453672018',
    projectId: 'lab10-80335',
    storageBucket: 'lab10-80335.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDknKRZCyK4Mzl05YE5GxCZm2_iFbSPJ0M',
    appId: '1:582453672018:ios:d94bfced70e79df557478b',
    messagingSenderId: '582453672018',
    projectId: 'lab10-80335',
    storageBucket: 'lab10-80335.firebasestorage.app',
    iosBundleId: 'com.example.lab10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDknKRZCyK4Mzl05YE5GxCZm2_iFbSPJ0M',
    appId: '1:582453672018:ios:d94bfced70e79df557478b',
    messagingSenderId: '582453672018',
    projectId: 'lab10-80335',
    storageBucket: 'lab10-80335.firebasestorage.app',
    iosBundleId: 'com.example.lab10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn-uiKeWj3dL07v4H5NU9zeANed_phla0',
    appId: '1:582453672018:web:a551e68bb612a2f157478b',
    messagingSenderId: '582453672018',
    projectId: 'lab10-80335',
    authDomain: 'lab10-80335.firebaseapp.com',
    storageBucket: 'lab10-80335.firebasestorage.app',
    measurementId: 'G-2YBVER4M9M',
  );
}
